### ISSUE TITLE
closed issue

### ISSUE THREAD

**Issue by scorp12** [maierfelix/POGOserver#247]
why was issue #242 closed

**Comment by DracoMilesX** [comment]
Most likely because their is al ready an open issue with the same problem(+ the tons of other node-gyp issues)

But to answer your problem for ubuntu vm.

Remove all pogo related files.

`passwd root` to create the password for the root user

logout and login as root with the password u set. Then redo the ubuntu setup.

It's a known issue that node-gyp fails under normal user/root combination so soley using a root user as above solves it. Issue is from 2014 or something. Can't find the workaround I originally did for it but it was a pain anyway.

**Comment by scorp12** [comment]
so far ive had good results once gksudo was installed and changed permissions of the files and folders. as alot of my issues was locked files. i had an issue and had to reinstall os lastnight. but will update more  once im back running

**Comment by scorp12** [comment]
the one error i had that i have to wait to reproduce was... err game-master

**Comment by Cronick** [comment]
Protobuf related issues will get closed.

**Comment by scorp12** [comment]
ban me from this. cronick ur an idiot. this is not a proyobuf issue. u dont answer shit here but u want to admin the issues page. ur making up rules as u go.
