### ISSUE TITLE
0•43•4 support

### ISSUE THREAD

**Issue by Lord-Haji** [maierfelix/POGOserver#302]
Many people has already cracked the API we should try that out too

**Comment by Cronick** [comment]
POGOserver has nothing to do with the API. POGOserver does not use the API at all.

**Comment by maierfelix** [comment]
Since this is an server emulator, it comes with an own "API" (equal to niantics), and just mimics the original one.
The server only depends on a similiar protobuf structure as the client expects.
If the google authentication process didnt changed, it should be possible to get this up working with the latest version.

**Comment by brunno0204** [comment]
@maierfelix Will you guys ever be able to fix this google authentication thingy?
